name: carsim
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - bidict==0.23.1
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dnspython==2.8.0
      - eventlet==0.40.4
      - filelock==3.19.1
      - flask==3.1.2
      - flask-socketio==5.5.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gast==0.4.0
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - idna==3.11
      - imageio==2.37.2
      - imgaug==0.4.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.4.2
      - numpy==2.2.6
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-engineio==3.13.2
      - python-socketio==4.6.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shapely==2.1.2
      - simple-websocket==1.1.0
      - simsimd==6.5.3
      - six==1.17.0
      - stringzilla==4.3.0
      - sympy==1.14.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - tf-estimator-nightly==2.8.0.dev2021122109
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.9.1+cpu
      - torchaudio==2.9.1+cpu
      - torchvision==0.24.1+cpu
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - wsproto==1.3.2
prefix: C:\Users\dell\miniconda3\envs\carsim